# Generated by Django 4.1.3 on 2022-11-08 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ('tag_name', '-id')},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_chapters', to='api.volume'),
        ),
        migrations.AlterField(
            model_name='title',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='title_tags', to='api.tags'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='volume_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_titles', to='api.title'),
        ),
    ]
